title: Admitchu
description: Visualize Your Path to Acceptance
url: "https://trustdan.github.io"
baseurl: "/admitchu-public"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md
  - privacy-policy.md

# Build settings
markdown: kramdown
